CREATE TABLE type_samples (
  c_integer INT NULL,
  c_smallint SMALLINT NULL,
  c_tinyint TINYINT NULL,
  c_mediumint MEDIUMINT NULL,
  c_bigint BIGINT NULL,
  c_bigint_identity BIGINT AUTO_INCREMENT NOT NULL,
  c_decimal DECIMAL(12,2) NULL,
  c_float FLOAT NULL,
  c_double DOUBLE NULL,
  c_char CHAR(10) NULL,
  c_varchar VARCHAR(255) NULL,
  c_text LONGTEXT NULL,
  c_bytea LONGBLOB NULL,
  c_binary BINARY(16) NULL,
  c_varbinary VARBINARY(255) NULL,
  c_boolean BOOLEAN NULL,
  c_date DATE NULL,
  c_time TIME(3) NULL,
  c_datetime DATETIME(6) NULL,
  c_timestamp TIMESTAMP NULL,
  c_year YEAR NULL,
  c_uuid UUID NULL,
  c_inet4 INET4 NULL,
  c_inet6 INET6 NULL,
  c_json JSON NULL,
  c_enum ENUM('draft','published') NULL,
  c_set SET('a','b') NULL,
  c_bit BIT(8) NULL,
  PRIMARY KEY (c_bigint_identity)
);