/* ------------------------- ddl: oracle ------------------------ */
/*
 * grabado: DesignModel -> Oracle 23ai の DDL（段階6-5a 移植 / 6-8c 現代化）。
 *
 * **独立実装。** js/io/ddl/ansi.ts にも mysql-style.ts にも載らない —— identity 列に
 * `GENERATED BY DEFAULT AS IDENTITY` を使う点は ansi 系と同じだが、識別子を**必ず**囲む
 * 必要があり（下）、キーをテーブル定義の中に置くところが違う。
 *
 * 6-8c で消えた upstream の粗さ（6-5a が記録したもの）:
 *
 *   1. **日本語識別子が裸で出る**（ora_ident の translate() は非 ASCII を変えない）
 *                                   -> naming.ts の quoteIdentifier に統一
 *   2. **複数列が autoincrement だと同名の CREATE SEQUENCE が重複**
 *                                   -> SEQUENCE ＋ TRIGGER をやめ、identity 列にした
 *   3. **PRIMARY / UNIQUE 以外の key type が ??INDEX?? という壊れた SQL になる**
 *                                   -> CREATE INDEX
 *   4. FK 名が FK_<tail13>_<tail13>（テーブル名を 13 文字で切る）
 *                                   -> fk_<table>_<列>（§6.3）
 *   5. DROP のコメントブロック（生成 DDL が既存データを消す手順を含む）-> 出さない
 *   6. 桁揃え（列名の長さで空白を詰める）                              -> 落とす（下）
 *
 * **桁揃えを落とした。** upstream の作り込みで読みやすさはあるが、**列名を 1 つ変えると
 * 無関係な行の空白まで動く**ので diff フレンドリー（CLAUDE.md 制約3）と噛み合わない。
 * 他 7 本とも揃う。
 *
 * **識別子は必ず囲まれる。** Oracle は引用符の無い識別子を大文字へ畳むので、house 標準の
 * snake_case を保つには全部囲むしかない（js/io/ddl/naming.ts の ORACLE_IDENTIFIER）。
 * 6-5b の「囲まないと意味が変わるものだけ囲む」の、いちばん広い側。
 *
 * **SEQUENCE ＋ TRIGGER をやめた**のは 12c で identity 列が入って以降その手順が要らない
 * ため。23ai を対象にする以上、11g 時代の書き方を出す理由が無い（実物で確認済み）。
 */

import { replaceSubstring, type DdlTable } from "./shared.ts";
import {
    ORACLE_IDENTIFIER,
    foreignKeyName,
    keyConstraintName,
    quoteIdentifier,
} from "./naming.ts";

/** 識別子を囲む。house 標準の小文字は**必ず**囲まれる（ORACLE_IDENTIFIER の bare は大文字） */
function q(name: string): string {
    return quoteIdentifier(name, ORACLE_IDENTIFIER);
}

/** 型名そのものが identity 句を持つか（パレットが句込みの型を持つ場合に二重を防ぐ） */
function hasIdentityClause(datatype: string): boolean {
    return /GENERATED\s+(ALWAYS|BY\s+DEFAULT)\s+AS\s+IDENTITY/i.test(datatype);
}

export function generateOracle(tables: readonly DdlTable[]): string {
    let out = "";

    for (const table of tables) {
        out += "CREATE TABLE " + q(table.name) + " (\n";

        const lines: string[] = [];
        for (const row of table.rows) {
            let line = "  " + q(row.name) + " " + row.datatype;

            /*
             * identity 列（12c 以降）。BY DEFAULT にしてあるのは、移行時に既存の値を
             * INSERT できる形が設計ツールの出力として扱いやすいため（ALWAYS だと拒まれる）。
             */
            const hasClause = hasIdentityClause(row.datatype);
            const identity = row.autoincrement || hasClause;
            if (identity && !hasClause) {
                line += " GENERATED BY DEFAULT AS IDENTITY";
            }
            /* identity 列に DEFAULT は付けられない（Oracle が拒む） */
            if (row.hasDefault && row.def !== "NULL" && !identity) {
                line += " DEFAULT " + row.def;
            }
            if (!row.nullable && !identity) {
                line += " NOT NULL";
            }
            lines.push(line);
        }

        /* キーはテーブル定義の中。PRIMARY / UNIQUE だけが制約で、他は下の CREATE INDEX */
        for (const key of table.keys) {
            if (key.parts.length === 0) {
                continue;
            }
            if (key.type !== "PRIMARY" && key.type !== "UNIQUE") {
                continue;
            }
            const name = q(keyConstraintName(key, table.name));
            const cols = key.parts.map(q).join(", ");
            const kind = key.type === "PRIMARY" ? "PRIMARY KEY" : "UNIQUE";
            lines.push("  CONSTRAINT " + name + " " + kind + " (" + cols + ")");
        }

        out += lines.join(",\n");
        out += "\n);\n\n";

        /* COMMENT ON は Oracle が持つ（sql-standard / mssql と違って行コメントに落とさない） */
        if (table.comment) {
            out +=
                "COMMENT ON TABLE " +
                q(table.name) +
                " IS '" +
                replaceSubstring(table.comment, "'", "''") +
                "';\n";
        }
        for (const row of table.rows) {
            if (row.comment) {
                out +=
                    "COMMENT ON COLUMN " +
                    q(table.name) +
                    "." +
                    q(row.name) +
                    " IS '" +
                    replaceSubstring(row.comment, "'", "''") +
                    "';\n";
            }
        }
        if (table.comment || table.rows.some((r) => r.comment)) {
            out += "\n";
        }
    }

    /* 索引。6-8c まで ??INDEX?? という壊れた SQL になっていた経路 */
    for (const table of tables) {
        for (const key of table.keys) {
            if (key.parts.length === 0) {
                continue;
            }
            if (key.type === "PRIMARY" || key.type === "UNIQUE") {
                continue;
            }
            out +=
                "CREATE INDEX " +
                q(keyConstraintName(key, table.name)) +
                " ON " +
                q(table.name) +
                " (" +
                key.parts.map(q).join(", ") +
                ");\n";
        }
    }

    /* FK は全テーブルを作り終えてから（前方参照を許すため）。名前は §6.3 の規約 */
    for (const table of tables) {
        for (const row of table.rows) {
            for (const rel of row.relations) {
                out +=
                    "ALTER TABLE " +
                    q(table.name) +
                    " ADD CONSTRAINT " +
                    q(foreignKeyName(table.name, row.name)) +
                    " FOREIGN KEY (" +
                    q(row.name) +
                    ") REFERENCES " +
                    q(rel.table) +
                    " (" +
                    q(rel.row) +
                    ");\n";
            }
        }
    }

    return out;
}
