CREATE TABLE [type_samples] (
  [c_integer] bigint ,
  [c_smallint] bigint ,
  [c_decimal] numeric(12,2) ,
  [c_serial] tinyint NOT NULL ,
  [c_bigserial] tinyint NOT NULL ,
  [c_float] float ,
  [c_double] tinyint ,
  [c_char] tinyint(10) ,
  [c_varchar] tinyint(255) ,
  [c_text] tinyint ,
  [c_bytea] tinyint ,
  [c_boolean] tinyint ,
  [c_date] tinyint ,
  [c_time] tinyint(3) ,
  [c_time_tz] tinyint ,
  [c_interval] bigint(6) ,
  [c_timestamp] tinyint(3) ,
  [c_timestamp_tz] tinyint ,
  [c_timestamp_wo_tz] tinyint ,
  [c_xml] tinyint ,
  [c_bit] tinyint(8) ,
  [c_varbit] tinyint(8) ,
  [c_inet] tinyint ,
  [c_cidr] tinyint ,
  [c_geometry] tinyint ,
  [c_json] tinyint ,
  [c_jsonb] tinyint , 
CONSTRAINT type_samples_pkey PRIMARY KEY ([c_serial])
) ON [PRIMARY]
GO