CREATE TABLE type_samples (
  c_integer int NOT NULL,
  c_smallint smallint,
  c_tinyint tinyint,
  c_bigint bigint,
  c_decimal decimal(12,2),
  c_float float,
  c_real real,
  c_char char(10),
  c_varchar varchar(255),
  c_nchar nchar(10),
  c_nvarchar nvarchar(255),
  c_boolean bit,
  c_binary binary(16),
  c_varbinary varbinary(255),
  c_date date,
  c_time time(3),
  c_datetime datetime,
  c_datetime2 datetime2(6),
  c_datetimeoffset datetimeoffset(6),
  c_smalldatetime smalldatetime,
  c_uuid uniqueidentifier,
  c_xml xml,
  c_sql_variant sql_variant,
  c_rowversion rowversion,
  c_hierarchyid hierarchyid,
  c_geometry geometry,
  CONSTRAINT type_samples_pkey PRIMARY KEY (c_integer)
);
GO