CREATE TABLE [type_samples] (
  [c_tinyint] tinyint ,
  [c_smallint] smallint ,
  [c_int] int NOT NULL ,
  [c_bigint] bigint ,
  [c_money] money ,
  [c_smallmoney] smallmoney ,
  [c_real] real ,
  [c_float] float ,
  [c_decimal] decimal(12,2) ,
  [c_numeric] numeric(18,4) ,
  [c_char] char ,
  [c_varchar] varchar(255) ,
  [c_text] text ,
  [c_xml] xml ,
  [c_nchar] nchar ,
  [c_nvarchar] nvarchar(255) ,
  [c_ntext] ntext ,
  [c_datetime] datetime ,
  [c_smalldatetime] smalldatetime ,
  [c_binary] binary ,
  [c_varbinary] varbinary(255) ,
  [c_bit] bit ,
  [c_image] image ,
  [c_timestamp] timestamp ,
  [c_sql_variant] sql_variant ,
  [c_uniqueidentifier] uniqueidentifier , 
CONSTRAINT type_samples_pkey PRIMARY KEY ([c_int])
) ON [PRIMARY]
GO