CREATE TABLE counters (
 id INTEGER GENERATED ALWAYS AS IDENTITY,
 label CHARACTER VARYING(64) NOT NULL,
 hits INTEGER NOT NULL DEFAULT 0
);


ALTER TABLE counters ADD CONSTRAINT counters_pkey PRIMARY KEY (id);