CREATE TABLE "type_samples" (
  "c_number" NUMBER(10) NOT NULL,
  "c_integer" INTEGER,
  "c_decimal" DECIMAL(12,2),
  "c_float" FLOAT(10),
  "c_binary_float" BINARY_FLOAT,
  "c_binary_double" BINARY_DOUBLE,
  "c_char" CHAR(10),
  "c_varchar2" VARCHAR2(255),
  "c_nchar" NCHAR(10),
  "c_nvarchar2" NVARCHAR2(255),
  "c_clob" CLOB,
  "c_nclob" NCLOB,
  "c_boolean" BOOLEAN,
  "c_date" DATE,
  "c_timestamp" TIMESTAMP(6),
  "c_timestamp_tz" TIMESTAMP WITH TIME ZONE,
  "c_interval_ym" INTERVAL YEAR TO MONTH,
  "c_interval_ds" INTERVAL DAY TO SECOND,
  "c_raw" RAW(16),
  "c_blob" BLOB,
  "c_json" JSON,
  "c_xml" XMLTYPE,
  "c_rowid" ROWID,
  CONSTRAINT "type_samples_pkey" PRIMARY KEY ("c_number")
);