CREATE TABLE 'type_samples' (
'c_integer' INTEGER,
'c_smallint' TEXT,
'c_decimal' TEXT(12,2),
'c_serial' TEXT NOT NULL  PRIMARY KEY,
'c_bigserial' TEXT NOT NULL ,
'c_float' TEXT,
'c_double' TEXT,
'c_char' TEXT(10),
'c_varchar' TEXT(255),
'c_text' TEXT,
'c_bytea' TEXT,
'c_boolean' TEXT,
'c_date' TEXT,
'c_time' TEXT(3),
'c_time_tz' TEXT,
'c_interval' TEXT(6),
'c_timestamp' TEXT(3),
'c_timestamp_tz' TEXT,
'c_timestamp_wo_tz' TEXT,
'c_xml' TEXT,
'c_bit' TEXT(8),
'c_varbit' TEXT(8),
'c_inet' TEXT,
'c_cidr' TEXT,
'c_geometry' TEXT,
'c_json' TEXT,
'c_jsonb' TEXT
);