CREATE TABLE 'type_samples' (
'c_integer' INTEGER DEFAULT NULL,
'c_smallint' TEXT DEFAULT NULL,
'c_decimal' TEXT(12,2) DEFAULT NULL,
'c_serial' TEXT NOT NULL  PRIMARY KEY,
'c_bigserial' TEXT NOT NULL ,
'c_float' TEXT DEFAULT NULL,
'c_double' TEXT DEFAULT NULL,
'c_char' TEXT(10) DEFAULT NULL,
'c_varchar' TEXT(255) DEFAULT NULL,
'c_text' TEXT DEFAULT NULL,
'c_bytea' TEXT DEFAULT NULL,
'c_boolean' TEXT DEFAULT NULL,
'c_date' TEXT DEFAULT NULL,
'c_time' TEXT(3) DEFAULT NULL,
'c_time_tz' TEXT DEFAULT NULL,
'c_interval' TEXT(6) DEFAULT NULL,
'c_timestamp' TEXT(3) DEFAULT NULL,
'c_timestamp_tz' TEXT DEFAULT NULL,
'c_timestamp_wo_tz' TEXT DEFAULT NULL,
'c_xml' TEXT DEFAULT NULL,
'c_bit' TEXT(8) DEFAULT NULL,
'c_varbit' TEXT(8) DEFAULT NULL,
'c_inet' TEXT DEFAULT NULL,
'c_cidr' TEXT DEFAULT NULL,
'c_geometry' TEXT DEFAULT NULL,
'c_json' TEXT DEFAULT NULL,
'c_jsonb' TEXT DEFAULT NULL
);